name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Debug Info
      run: |
        echo "Current directory: $(pwd)"
        ls -al

    - name: Build and publish the API
      run: |
        dotnet publish -c Release -o ./publish
      working-directory: /home/runner/work/HexaLambdaAuthorization/HexaLambdaAuthorization
      
    - name: Zip Files
      run: |
        cd ./publish
        zip -r HexaLambdaAuthorization.zip *
      working-directory: /home/runner/work/HexaLambdaAuthorization/HexaLambdaAuthorization
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lambda-zip
        path: /home/runner/work/HexaLambdaAuthorization/HexaLambdaAuthorization/publish/HexaLambdaAuthorization.zip

    - name: Verify ZIP File
      run: |
        if [ -f ./publish/HexaLambdaAuthorization.zip ]; then
          echo "ZIP file exists."
        else
          echo "ZIP file does not exist."
        fi
      working-directory: /home/runner/work/HexaLambdaAuthorization/HexaLambdaAuthorization
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Upload ZIP to S3
      run: |
        aws s3 cp ./publish/HexaLambdaAuthorization.zip s3://hexalambda/zipcode/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name HexaLambdaAuthorization --zip-file fileb://./publish/HexaLambdaAuthorization.zip
      env:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
